Add export database schema option to the settings page on console  (close #2371)
hasura/graphql-engine pull request #5420
Opened 2020-07-20 03:42 UTC by soorajshankar

Add export database schema option to the settings page on console  (close #2371)

### Description
console now support DB schema export, which allows the user to download database schema using [pg_dump](https://hasura.io/docs/1.0/graphql/manual/api-reference/pgdump.html#id1) api.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Console

### Related Issues
close #2371 

### Solution and Design
> pg_dump API is used to fetch the data and the data is downloaded as `db.sql` file.

### Steps to test and verify
1. go to settings page
2. click on download schema button 
3. user should be able to download a DB SQL file.
![image](https://user-images.githubusercontent.com/8408875/87897375-c3496c80-ca68-11ea-8dab-946718d7b7f0.png)

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No

#### Metadata
Does this PR add a new Metadata feature?
- [x] No

#### GraphQL
- [x] No new GraphQL schema is generated

#### Breaking changes

- [x] No Breaking changes

2020-08-03 16:15 UTC, beerose commented on console/src/components/Common/utils/v1QueryUtils.ts
> +  opts: ['-O', '-x', '--schema-only', '--schema', 'public'],
So this will only work for public schemas?

2020-08-03 16:17 UTC, beerose commented on console/src/components/Services/Settings/MetadataOptions/MetadataOptions.js
> +    exportSchema: () => dispatch(exportSchema()),
```suggestion
    exportSchema: () => dispatch(exportSchema),
```

and simplify `exportSchema`.

2020-08-03 16:17 UTC, beerose commented on console/src/components/Services/Settings/Actions.js
> +export const exportSchema = () => (dispatch, getState) => {
```suggestion
export const exportSchema => (dispatch, getState) => {
```

It's not taking any arguments anyway.

2020-09-01 09:35 UTC, beerose approved these changes
Console

2020-09-14 10:10 UTC, beerose requested changes
Having components inside of a component causes render issues as React is unable to reconcile the rendering of these components. They will be treated as new components every time.

There is a minimal repro with buggy behaviour: https://codesandbox.io/s/react-nested-functional-components-lvl85?file=/src/App.tsx
Try to type more than one digit inside of input and see what happens. You can also see how it would behave if it was called as a function instead of a component.

2020-09-14 10:10 UTC, beerose commented on console/src/components/Services/Settings/MetadataOptions/MetadataOptions.js
> +  const MetadataImportExportSection = () => {
Can you move it outside of the component? Having components inside of components causes render issues as React will be unable to reconcile the rendering of these components, as they are treated as new components every time.

2020-09-14 10:10 UTC, beerose commented on console/src/components/Services/Settings/MetadataOptions/MetadataOptions.js
> +  const MetadataUpdateSection = () => {
Same

2020-11-05 09:35 UTC, mnlbox commented
@beerose Any news form this PR?

2020-11-11 18:59 UTC, beerose approved these changes
Console

2021-08-19 15:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=5420) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=5420) before we can accept your contribution.<br/>**1** out of **2** committers have signed the CLA.<br/><br/>:white_check_mark: soorajshankar<br/>:x: Aleksandra Sikora<br/><hr/>**Aleksandra Sikora** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=5420) it.</sub>

2023-06-14 06:42 UTC, closed without merging