added export data option on data module (close #1438)
hasura/graphql-engine pull request #5440
Opened 2020-07-22 06:37 UTC by soorajshankar

### Description
This PR adds a feature that allows Hasura console users to export the data to JSON or CSV file. 

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components
- [x] Console

### Related Issues
close #1438 

### Solution and Design
A query with the filter is used to hit hasura backend, which will not have `limit` / `offset` so all the entries with the applied filter can be retrieved from the server. this data is hence processed to the required format (JSON/CSV).  

### Steps to test and verify
![image](https://user-images.githubusercontent.com/8408875/88142265-d6983b80-cc12-11ea-900e-c51564f41885.png)

* User can now go to data module and see the export button as shown
* By clicking the export option, CSV/JSON download should start with the correct data.

### Limitations, known bugs & workarounds
* since we are fetching all the data without a limit, large tables might have a performance issue.

### Server checklist

#### Catalog upgrade
- [x] No

#### Metadata
Does this PR add a new Metadata feature?
- [x] No

#### GraphQL
- [x] No new GraphQL schema is generated

#### Breaking changes

- [x] No Breaking changes

2020-08-24 12:36 UTC, rikinsk requested changes
UX looks fine.

Observed a bug when exporting data as csv 
![Screenshot from 2020-08-24 18-06-30](https://user-images.githubusercontent.com/54616969/91045471-8f97ce80-e634-11ea-8e68-6a1842c4e5b0.png)
for array relationships. Array data gets exports as `[object Object]`

![Screenshot from 2020-08-24 18-04-41](https://user-images.githubusercontent.com/54616969/91045393-6ecf7900-e634-11ea-8bb6-294c826b6c45.png)

2020-09-04 07:08 UTC, soorajshankar commented
@rikinsk fixed the above changes, now the export will look like this.
Let me know your thoughts

![image](https://user-images.githubusercontent.com/8408875/92209699-15c0da00-eeab-11ea-9200-61acb068e1e3.png)

2021-01-15 08:48 UTC, beerose commented on console/src/components/Services/Data/TableBrowseRows/FilterActions.js
> +    console.log(tableSchema);
Reminder

2021-01-18 09:11 UTC, beerose commented on CHANGELOG.md
> +- console: added export data option on data module (close #1438 #5158)
Fix

2021-01-22 13:53 UTC, closed without merging