docs: add inserts to db modelling guides
hasura/graphql-engine pull request #5444
Opened 2020-07-22 09:22 UTC by marionschleifer

### Description

Based on repeated docs feedback, users are sometimes confused as to how to insert data after going through the [database modelling guides](https://hasura.io/docs/1.0/graphql/manual/schema/table-relationships/database-modelling/index.html).

This PR adds examples for inserts for all three guides.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Docs

2020-08-06 07:09 UTC, marionschleifer commented
@rikinsk can you please give your feedback regarding flow?

2020-10-06 12:49 UTC, rikinsk approved these changes

2020-10-06 12:59 UTC, rikinsk requested changes
@marionschleifer we should also add an example each for the cases where the nested object might already exist using the on_conflict clause. we can assume a particular idenitifier to have a unique constraint to use in the on_conflict clause

- one-to-one - insert passport_infos with their owner which might already exist (assume unique name for user)
- one-to-many - insert articles with their author which might already exist (assume unique name for author)
- many-to-many - insert a list of articles with their tags which might already exist (assume unique tag_value for tag)

2020-10-23 19:05 UTC, marionschleifer commented
@rikinsk I added the examples. For the one-to-many and for the many-to-many, I showed examples from "both sides". Let me know if you think it's overkill.

2020-11-30 11:39 UTC, codeliezel approved these changes

2021-02-02 08:04 UTC, rikinsk approved these changes

2021-02-02 08:45 UTC, closed without merging