console: show session argument input for computed fields
hasura/graphql-engine pull request #5610
Opened 2020-08-18 07:02 UTC by kolharsam

closes #5154 

### Description

This PR mainly adds a new input field for including a session argument for computed fields. This PR also includes minor fixes and also TS migration of the `ComputedFieldsEditor` file

### Changelog (TODO)

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [x] Console

2020-09-29 08:57 UTC, soorajshankar approved these changes
The code looks good, left a minor commend but **Do as you wish**


Observations and steps that I followed to test 
---
1. Run and track the following SQL

```sql
CREATE TABLE public.article (
    id integer NOT NULL,
    book text NOT NULL,
    author integer NOT NULL
);

CREATE TABLE public.article_likes (
    user_id integer NOT NULL,
    article_id integer NOT NULL,
    id integer NOT NULL
);

CREATE TABLE public.author (
    first_name text NOT NULL,
    last_name text NOT NULL,
    id integer NOT NULL
);
CREATE SEQUENCE public.article_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.article_id_seq OWNED BY public.article.id;

CREATE SEQUENCE public.article_likes_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.article_likes_id_seq OWNED BY public.article_likes.id;
CREATE SEQUENCE public.author_id_seq
    AS integer
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1;
ALTER SEQUENCE public.author_id_seq OWNED BY public.author.id;
ALTER TABLE ONLY public.article ALTER COLUMN id SET DEFAULT nextval('public.article_id_seq'::regclass);
ALTER TABLE ONLY public.article_likes ALTER COLUMN id SET DEFAULT nextval('public.article_likes_id_seq'::regclass);
ALTER TABLE ONLY public.author ALTER COLUMN id SET DEFAULT nextval('public.author_id_seq'::regclass);
ALTER TABLE ONLY public.article_likes
    ADD CONSTRAINT article_likes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.author
    ADD CONSTRAINT author_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.article
    ADD CONSTRAINT article_author_fkey FOREIGN KEY (author) REFERENCES public.author(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE ONLY public.article_likes
    ADD CONSTRAINT article_likes_article_id_fkey FOREIGN KEY (article_id) REFERENCES public.article(id) ON UPDATE RESTRICT ON DELETE RESTRICT;
ALTER TABLE ONLY public.article_likes
    ADD CONSTRAINT article_likes_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.author(id) ON UPDATE RESTRICT ON DELETE RESTRICT;


INSERT INTO "public"."author" ("first_name", "last_name") VALUES ('sooraj', 'sanker');
INSERT INTO "public"."article" ("book", "author") VALUES ('test book', '1');
INSERT INTO "public"."article_likes" ("user_id", "article_id") VALUES ('1', '1');
```

2. Run the following without tracking it

```sql
CREATE FUNCTION public.article_liked_by_user(article_row public.article, hasura_session json) RETURNS boolean
    LANGUAGE sql STABLE
    AS $$
SELECT EXISTS (
    SELECT 1
    FROM article_likes A
    WHERE A.user_id :: text= hasura_session ->> 'x-hasura-user-id' AND A.article_id = article_row.id
);
$$;
```


Add computed field on `articles` table, name it `article_liked_by_user`, add `hasura_session` as session argument

Test the computed field from the gql explorer by passing `x-hasura-user-id = 1`
expected o/p
![image](https://user-images.githubusercontent.com/8408875/94535637-6d125a00-025f-11eb-82d4-8e03efd6c3de.png)


> Note: Functions added as computed fields are filtered from the `trackable_functions` list, this can be tested with a function that returns `SETOF<table>`

2020-10-16 12:45 UTC, beerose requested changes
Left a few, mostly minor, comments.

The functionality looks good.

2020-10-16 12:45 UTC, beerose commented on CHANGELOG.md
> +- console: add `<3 hasura` section to view updates and notifications from Hasura (#5070)
```suggestion
```

2020-10-16 12:45 UTC, beerose commented on console/src/components/Services/ApiExplorer/OneGraphExplorer/OneGraphExplorer.js
> +        console.error(err, err.message);
```suggestion
```

2020-10-16 12:45 UTC, beerose commented on console/src/components/Services/Data/TableModify/ComputedFieldsEditor.tsx
> +              <Tooltip message="the function argument into which hasura session variables will be passed" />
```suggestion
              <Tooltip message="The function argument into which Hasura session variables will be passed" />
```

2020-10-16 12:45 UTC, beerose commented on console/src/components/Services/Data/TableModify/ComputedFieldsEditor.tsx
> +          dispatch(fetchFunctionInit((selectedOption as OptionTypeBase).value));
Can you get rid of type assertion and do a check for `value` field here?

2020-10-16 12:45 UTC, beerose commented on console/src/components/Services/Data/TableModify/ComputedFieldsEditor.tsx
> +              schema: (selectedOption as OptionTypeBase).value,
Same

2020-10-16 12:45 UTC, beerose commented on console/src/components/Services/Data/TableModify/ComputedFieldsEditor.tsx
> +              name: (selectedOption as OptionTypeBase).value,
Same

2020-10-16 12:45 UTC, beerose commented on console/src/components/Services/Data/TableModify/ComputedFieldsEditor.tsx
> +        .filter(fn => !trackedFunctionNames.includes(fn.function_name))
```suggestion
```

2020-10-16 12:45 UTC, beerose commented on console/src/components/Services/Data/TableModify/ComputedFieldsEditor.tsx
> +    ) as TableDefinition;
Can you get rid of type assertions?

2020-10-16 12:45 UTC, beerose commented on console/src/components/Services/Data/TableModify/ComputedFieldsEditor.tsx
> +      ) as TableDefinition;
Can you get rid of type assertions?

2020-10-16 12:45 UTC, beerose commented on console/src/components/Services/Data/Schema/Schema.js
> +      );
leaving it as a reminder 
```suggestion
```

2020-10-16 12:45 UTC, beerose commented on console/src/components/Services/Data/TableModify/ModifyTable.js
> +  trackedFunctions: state.tables.trackedFunctions,
```suggestion
```

2020-10-19 10:43 UTC, beerose commented on console/src/components/Services/Data/TableModify/ComputedFieldsEditor.tsx
> +      }
A user might have removed a comment. In this case, `origComputedField.comment` would be falsy. As if condition would be `false` for it, then we won't be able to remove a comment.

2020-11-12 13:18 UTC, beerose approved these changes
Console

2021-01-28 00:00 UTC, closed without merging