Better secret handling in Auth0 rule
hasura/graphql-engine pull request #5677
Opened 2020-08-27 02:16 UTC by samuela

### Description

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

### Solution and Design

### Steps to test and verify

### Limitations, known bugs & workarounds

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2020-09-14 13:53 UTC, marionschleifer requested changes

2020-09-14 13:53 UTC, marionschleifer commented on docs/graphql/core/guides/integrations/auth0-jwt.rst
> +And add make sure to specify the `HASURA_ADMIN_SECRET` variable in the "Rules > Settings" section of Auth0. That’s it! This rule will be triggered on every successful signup/login and sync your Auth0
```suggestion
Make sure to specify the `HASURA_ADMIN_SECRET` variable in the "Rules > Settings" section of Auth0. 

That’s it! This rule will be triggered on every successful signup/login and sync your Auth0 user into your postgres database.
```

2020-09-28 10:20 UTC, marionschleifer approved these changes

2020-10-01 12:36 UTC, rikinsk approved these changes

2020-10-01 13:14 UTC, merged