Console: Role names with white spaces
hasura/graphql-engine pull request #5748
Opened 2020-09-08 18:32 UTC by abhi40308

Earlier, when creating a role in permissions, we could not give whitespaces, as whitespaces were getting trimmed. This pull request fixes that issue.

### Description

fix #5553 

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

### Solution and Design

### Steps to test and verify

Go to data section, select a table and select permissions, create a role with whitespace in it. For example `admin role`.

### Limitations, known bugs & workarounds

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2020-09-08 18:32 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=5748) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=5748) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=5748) it.</sub>

2020-09-10 17:43 UTC, beerose requested changes

2020-09-10 17:43 UTC, beerose commented on console/src/components/Services/Data/TablePermissions/Actions.js
> +    const role = permissionsState.role.replace(/ /g, '');
```suggestion
    const role = permissionsState.role.trim();
```

2020-09-10 17:44 UTC, beerose commented on console/src/components/Services/Data/TablePermissions/Actions.js
> +    const role = permissionsState.role.replace(/ /g, '');
Doing replace whitespaces won't solve the original issue.

2020-09-14 16:25 UTC, beerose approved these changes
Console

2020-09-15 11:19 UTC, tirumaraiselvan approved these changes
A changelog might have been good since it's a user reported issue so it's definitely user-facing ;)

But, it's also very trivial so it's okay.

2020-09-24 07:28 UTC, merged