console: trim migration names exceeding 255 characters (close #4403)
hasura/graphql-engine pull request #5785
Opened 2020-09-15 06:33 UTC by abhi40308

Migration name longer than 255 characters lead to unpredictable behaviour due to filename character limits.

### Description

fix #4403

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [x] Console
- [x] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

### Solution and Design

### Steps to test and verify

Open hasura console, create a table with long name and some columns with long column names, then try creating a constraint (say unique key) on a combination of columns.

### Limitations, known bugs & workarounds

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2020-09-15 06:33 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=5785) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=5785) before we can accept your contribution.<br/><hr/>**Abhijeet SIngh Khangarot** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=5785) it.</sub>

2020-09-25 11:07 UTC, soorajshankar requested changes
The console is still failing with the following steps.
1. Go to console > Create Table 
2. Try creating a table with name "test_test_test_test_test_test_test_test_test_test_test_test_test_123" (length greater than 63 chars)
3. console is getting crashed

Note: Adding a front-end char length validation might resolve this.

Also noticed the migration is getting created with the full table name, while pg is still truncating the name to 63 chars

--
>The system uses no more than NAMEDATALEN-1 bytes of an identifier; longer names can be written in commands, but they will be truncated. By default, NAMEDATALEN is 64 so the maximum identifier length is 63 bytes. If this limit is problematic, it can be raised by changing the NAMEDATALEN constant in src/include/pg_config_manual.h.

source : https://www.postgresql.org/docs/current/sql-syntax-lexical.html#SQL-SYNTAX-IDENTIFIERS

2020-10-20 06:20 UTC, soorajshankar requested changes
@abhi40308 I was testing the functionality, I found that the UI is trimming the migration length and sending the correct value to both migrations and the PG.

But when the user performs this action, the user is nowhere notified that the name is getting truncated. and the text input is having the full length but the moment when we submit, it gets truncated without letting the user know.

What I was expecting is to show a front end field validation, so that the user could only type characters with a maximum limit (text validation) 

It would be great if we can make inline validation or we can continue showing the notification (like if you put a space on the table name, it would show an error notification when you try to submit)

2020-11-02 06:47 UTC, soorajshankar approved these changes

2021-05-31 13:56 UTC, abhi40308 commented
Closing in favour of https://github.com/hasura/graphql-engine-mono/pull/1360

2021-06-02 10:24 UTC, closed without merging