console: top nav UI bug fixes (close #3680)
hasura/graphql-engine pull request #5798
Opened 2020-09-17 08:22 UTC by abhi40308

Earlier, when resizing the window, the gear and help icons would go out of window, this pull request fixes that issue.

### Description
fix #3680 

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

### Solution and Design
New Behavior: 
![ezgif com-gif-maker](https://user-images.githubusercontent.com/26903230/93439912-bf14c080-f8ec-11ea-8b5f-aa8f696a5cd6.gif)

### Steps to test and verify
Try resizing the window and check header navbar.

### Limitations, known bugs & workarounds

2020-09-17 10:59 UTC, kolharsam approved these changes
Looks great! 👌

2020-09-29 16:47 UTC, beerose requested changes
Instead of hiding `secure section`, please do the same as with another sidebar items — show icon, hide text.

2020-10-06 20:03 UTC, beerose approved these changes
Console

2020-10-06 21:18 UTC, beerose commented on console/src/components/Main/Main.js
> +              <span className={styles.secureSectionText}>&nbsp;Secure your endpoint</span>
```suggestion
              <span className={styles.secureSectionText}>
                &nbsp;Secure your endpoint
              </span>
```

2020-10-07 08:35 UTC, beerose commented on console/src/components/Main/Main.scss
> +@media (max-width: 1000px) {
```suggestion
@media (max-width: 1050px) {
```

2020-10-07 11:31 UTC, merged