Refractor GQL Api to support Automated Persisted Queries in pro
hasura/graphql-engine pull request #5804
Opened 2020-09-18 09:32 UTC by Naveenaidu

### Description
Refractor the Graphql API to support Automated Persisted Queries

### Affected components

- [x] Server

2020-09-21 07:06 UTC, ecthiender requested changes
Overall LGTM. I only had some minor comments.

2020-09-21 07:06 UTC, ecthiender commented on server/src-lib/Hasura/Server/App.hs
> +class Monad m => MonadGQLApiHandler m where
@Naveenaidu can you add some comments describing what is this for?

2020-09-21 07:06 UTC, ecthiender commented on server/src-lib/Hasura/Server/App.hs
> +      )
I think its a good idea to add these constraints to the `runGQLApiHandler` function as well.

2020-09-21 07:06 UTC, ecthiender commented on server/src-lib/Hasura/Server/App.hs
> +      runGQLApiHandler serverCtx
Maybe adding the following comment will help the future reader understand what's going on?

```suggestion
      -- See 'MonadGQLApiHandler'
      runGQLApiHandler serverCtx 
```

2020-09-21 07:06 UTC, ecthiender commented on server/src-lib/Hasura/Server/App.hs
>  -- instance (MonadIO m, UserAuthentication m, HttpLog m, Tracing.HasReporter m) => MonadConfigApiHandler (Tracing.TraceT m) where
Also this is unrelated to your PR. But I think let's remove this commented out code.

2020-09-21 13:42 UTC, ecthiender commented
I think we should also add a default GET handler to execute graphql queries. It should expect `query`, `variables` and `operationName` as URL query string parameters. @0x777 @paf31 what do you think?

2020-09-21 18:15 UTC, paf31 approved these changes

2023-07-24 13:16 UTC, Stefmore02 commented
Closing this PR as changes reflected here have already been implemented.

2023-07-24 13:16 UTC, closed without merging