Remote Schema Permissions (Role based only)
hasura/graphql-engine pull request #5867
Opened 2020-09-30 06:41 UTC by codingkarthik

PR for Role based remote schema permissions, [RFC](https://github.com/tirumaraiselvan/graphql-engine/blob/rfc-remote-schema-perms/rfcs/remote-schema-permissions.md)

TODO:

[] Response Validation
[] Feature flag for enabling remote schema permissions
[] Tests
[] docs

### Description

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

### Solution and Design

### Steps to test and verify

### Limitations, known bugs & workarounds

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2020-10-23 04:28 UTC, soorajshankar commented on docs/graphql/core/api-reference/schema-metadata-api/remote-schema-permissions.rst
> +part of the upstram remote schema for each role. By default, the ``admin`` role
```suggestion
part of the upstream remote schema for each role. By default, the ``admin`` role
```

2020-10-26 07:22 UTC, marionschleifer requested changes

2020-10-26 07:22 UTC, marionschleifer commented on docs/graphql/core/api-reference/schema-metadata-api/index.rst
> +  Remote Schema Permission <remote-schema-permissions>
```suggestion
  Remote Schema Permissions <remote-schema-permissions>
```

2020-10-26 07:22 UTC, marionschleifer commented on docs/graphql/core/api-reference/schema-metadata-api/remote-schema-permissions.rst
> +A remote schema permission is used to enforce constraints on the query that's
```suggestion
A remote schema permission is used to enforce constraints on queries
```

2020-10-26 07:22 UTC, marionschleifer commented on docs/graphql/core/api-reference/schema-metadata-api/remote-schema-permissions.rst
> +being queried to the remote schema. This is done by specifying the schema document
```suggestion
to the remote schema. This is done by specifying the schema document
```

2020-10-26 07:22 UTC, marionschleifer commented on docs/graphql/core/api-reference/schema-metadata-api/remote-schema-permissions.rst
> +2. Allow filtering of the messages only by ``name`` in the ``whered`` argument
```suggestion
2. Allow filtering of the messages only by ``name`` in the ``where`` argument
```

2020-10-26 07:22 UTC, marionschleifer commented on docs/graphql/core/api-reference/schema-metadata-api/remote-schema-permissions.rst
> +3. Allow only ``hello``, ``messages`` and the ``user`` top level node in the ``Query`` object.
```suggestion
3. Allow only the fields ``hello``, ``messages`` and the ``user`` top level node in the ``Query`` object.
```

2020-10-26 07:22 UTC, marionschleifer commented on docs/graphql/core/api-reference/schema-metadata-api/remote-schema-permissions.rst
> +     - The permission definition
```suggestion
     - The remote schema permission definition
```

2020-10-26 07:22 UTC, marionschleifer commented on docs/graphql/core/api-reference/schema-metadata-api/remote-schema-permissions.rst
> +   with ``--enable-remote-schema-permissions`` server flag or by setting the   ``HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS`` environment variable.
```suggestion
   with the ``--enable-remote-schema-permissions`` server flag or by setting the   ``HASURA_GRAPHQL_ENABLE_REMOTE_SCHEMA_PERMISSIONS`` environment variable.
```

2020-10-29 06:30 UTC, codingkarthik commented
Closing this PR, the features of this PR are included in https://github.com/hasura/graphql-engine/pull/6079

2020-10-29 06:30 UTC, closed without merging