Console: Added a Loading Spinner for Graphiql to indicates that introspection is in progress
hasura/graphql-engine pull request #5873
Opened 2020-10-01 08:29 UTC by Varun-Choudhary

Closes: #2485 

### Description

Earlier while the schemas are loading on Explorer on Graphiql console, it says NO SCHEMA AVAILABLE. This PR added a loading spinner with text "Loading...Schema" while the schemas are loading.

### Affected components

- [X] Console

2020-10-14 20:28 UTC, beerose requested changes

2020-10-14 20:28 UTC, beerose commented on console/src/components/Services/ApiExplorer/OneGraphExplorer/OneGraphExplorer.js
> +    ) : (
Could you leave only Spinner, and remove `Loading ...` text?

Also, apply those styles to the parent div:
```
    width: 300px;
    display: flex;
    align-items: center;
    height: 100%;
```

There are already classes for it so you'd need to use:
* .wd300Px
* .display_flex
* .height100

```jsx
<div className={`${styled.height100} ${styles.display_flex} ${styles.wd300Px}`}> ....
```

2020-11-11 19:06 UTC, beerose approved these changes
Console

2020-12-08 12:53 UTC, beerose commented on console/src/components/Services/ApiExplorer/OneGraphExplorer/OneGraphExplorer.js
> +          {!this.props.loading ? (
```suggestion
          {this.props.loading ? (
```

2020-12-08 13:07 UTC, rikinsk approved these changes

2021-03-10 20:10 UTC, closed without merging