console: add option to flag an edit row as a migration
hasura/graphql-engine pull request #5874
Opened 2020-10-01 10:19 UTC by Varun-Choudhary

Closes: #490

### Description

This PR add a `this a migration` checkbox to `Edit Row` to indicate that the current edited row is also a migration

### Changelog

- [X] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [X] Console

### Solution and Design

A checkbox has been added to the "Edit Row" section of the Schema page.

### Steps to test and verify

Start the console in cli mode and try inserting data into tables.

### Related Issues

https://github.com/Varun-Choudhary/graphql-engine

2020-10-16 16:35 UTC, beerose requested changes
It looks good overall. I found one issue, tho.

If you modify a primary key, then the down migrations won't be correct. 

Example:
Let's say you have a table `user` with columns `id -- Primary Key, name` and the following row:
```
id: 1, name: "test_name"
```
Now, you modify this row to be:
```
id: 10, name: "test_name" <-- PK column was changed
```
The generated migrations will look more or less like this:
```
// UP

update table users set id = 10 where id = 1;

// DOWN
update table users set id = 1 where id = 1;
```
The down migration won't have any effect, because there's no row with `id=1` anymore. 

The same would go for tables with no PK, where we generate `where` clause based on all the columns.

The solution would be to determine whether PK was changed and use the proper where clause in down migration.

2020-10-19 04:59 UTC, Varun-Choudhary commented
@beerose

2020-10-19 05:00 UTC, Varun-Choudhary commented
@beerose                                                                                                                                                                                                     How you were able to edit the ID?

2020-10-20 11:31 UTC, kolharsam requested changes
Leaving some comments for your reference. @Varun-Choudhary

2020-10-20 11:31 UTC, kolharsam commented on console/src/components/Services/Data/TableBrowseRows/EditActions.js
> +  const upQuery = getEditRowQuery(tableDef, newItem, columns, pkClause);
```suggestion
  const upQuery = getEditRowQuery(tableDef, newItem, columns, oldItem);
```

2020-10-20 11:31 UTC, kolharsam commented on console/src/components/Services/Data/TableBrowseRows/EditActions.js
> +  const downQuery = getEditRowQuery(tableDef, oldItem, columns, pkClause);
```suggestion
  const downQuery = getEditRowQuery(tableDef, oldItem, columns, newItem);
```

2020-10-20 11:31 UTC, kolharsam commented on console/src/components/Services/Data/TableBrowseRows/EditActions.js
> +  pkClause,
remove from function definition

2020-10-20 11:31 UTC, kolharsam commented on console/src/components/Services/Data/TableBrowseRows/EditActions.js
> +              pkClause,
remove

2020-10-20 11:31 UTC, kolharsam commented on console/src/components/Services/Data/TableBrowseRows/EditActions.js
> +        where: pkClause,
Do not use `pkClause` for this. Write a function to change the elements of `oldItem` to a where clause. 
The function can be defined like so:

```javascript
const makeWhereClause = (oldItem) => {
     const listOfElems = [];
     const oldItemKeys = Object.keys(oldItem);
     oldItemKeys.forEach(key => {
            listOfElems.push({ [key]: { '$eq': oldItem[key] } }) 
      });
     
     return {
         '$and': listOfElems,
     };
}
```

2020-10-20 11:31 UTC, kolharsam commented on console/src/components/Services/Data/TableBrowseRows/EditActions.js
> +    const { pkClause, oldItem } = state.tables.update;
```suggestion
    const { oldItem } = state.tables.update;
    const newWhereClause = makeWhereClause(oldItem);
```

2020-10-20 11:31 UTC, kolharsam commented on console/src/components/Services/Data/TableBrowseRows/EditActions.js
> +        where: pkClause,
use `newWhereClause` from above, instead of `pkClause`

2020-10-20 11:31 UTC, kolharsam commented on console/src/components/Common/utils/v1QueryUtils.ts
> +  const clauses = Object.keys(pkClause).map(pk =>
this might break some cases. please be sure to test and check the working of this method upon making all of these changes.

2020-11-02 08:49 UTC, beerose commented
@Varun-Choudhary Could you check failing console tests?

2020-11-12 19:11 UTC, kolharsam approved these changes

2020-11-17 12:03 UTC, beerose requested changes
I noticed that you stopped using primary key info to generate where clause. 

Let's take a look at some examples and the expected behaviour:

### Table with PK

```
table: user
columns: email (PK), name, age

entries in DB:
ola@ola.com, ola, null
```

Now, I want to edit my DB entry and mark it as migration. PK can be modifiable, so there are two scenarios (if PK wasn't modifiable, e.g. it was auto-generated, we would have only 1. scenario):

**1. I'm editing `name`, leaving `email (PK)` as it was:**
```
// rql
{
 type: 'update',
    args: {
      table: {
        name: 'users',
      },
      where: {
        email: 'ola@ola.com',
      },
      $set: {
        name: 'aleksandra',
      },
    },
  }
}
```
The where clause should ONLY consist of columns that are primary keys. In this case, it's `email`.
Up and down migrations:
```sql
-- up

update table users set name="aleksandra" where email="ola@ola.com";

-- down

update table users set name="ola" where email="ola@ola.com";
```

**2. I'm also editing PK:**
```
// rql
{
 type: 'update',
    args: {
      table: {
        name: 'users',
      },
      where: {
        email: 'ola@ola.com',
      },
      $set: {
        name: 'aleksandra',
        email: 'aleksandra@aleksandra.com',
      },
    },
  }
}
```

Up and down migrations should look as follow:

```sql
-- up

update table users set name="aleksandra", email="aleksandra@aleksandra.com" where email="ola@ola.com";  -- USING ORIGINAL PK

-- down

update table users set name="ola", email="ola@ola.com" where email="aleksandra@aleksandra.com"; -- USING NEW PK, BECAUSE WE WANT TO REVERT 
```

---

### Tables without PK

The current behaviour should be applied — where clause should consist of all columns.

2021-08-19 15:10 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=5874) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=5874) before we can accept your contribution.<br/>**2** out of **3** committers have signed the CLA.<br/><br/>:white_check_mark: kolharsam<br/>:white_check_mark: Varun-Choudhary<br/>:x: Aleksandra Sikora<br/><hr/>**Aleksandra Sikora** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=5874) it.</sub>

2023-07-11 13:06 UTC, Stefmore02 commented
Closing this PR as it's not relevant anymore.

2023-07-11 13:06 UTC, closed without merging