add: spanish CONTRIBUTING.md translation
hasura/graphql-engine pull request #5883
Opened 2020-10-02 21:09 UTC by iamthismarvin

### Description

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [ ] Console
- [ ] CLI
- [x] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

#5851 

### Solution and Design

### Steps to test and verify

### Limitations, known bugs & workarounds

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2020-10-02 21:09 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=5883) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=5883) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=5883) it.</sub>

2020-10-12 01:10 UTC, y-martinez requested changes
Hola revisaba tu PR, te hice unas observaciones :)

2020-10-12 01:10 UTC, y-martinez commented on translations/CONTRIBUTING.mx_spanish.md
> +- Haga squash a sus commits y consulte el issue usando `fix # <issue-no>` o `close # <issue-no>` en el mensaje de confirmación, al final.
Si traduces en todo el doc `issue` deberías de seguir haciéndolo. En este caso particular el consulte se debería de cambiar a `y enlace el issue usando` o también `y refiera al issue usando`

2020-10-12 01:10 UTC, y-martinez commented on translations/CONTRIBUTING.mx_spanish.md
> +## 6. Confirmar mensajes
Commit es una palabra complicada de traducir, particularmente en el argot de la tecnología pienso que no debería de traducirse, sin embargo, si la quieres traducir deberías de reescribirlo a algo como `Mensajes de confirmación` ya que el punto hablar de los mensajes si lo dejas como está se entiende de otra manera

2020-10-12 01:10 UTC, y-martinez commented on translations/CONTRIBUTING.mx_spanish.md
> +- [Boilerplates](https://github.com/hasura/graphql-engine/tree/master/community/boilerplates)
Boilerplates tiene traducción, a plantillas

2020-10-12 01:10 UTC, y-martinez commented on translations/CONTRIBUTING.mx_spanish.md
> +Sin embargo, para aquellas personas que deseen un poco más de orientación sobre la mejor manera de contribuir al proyecto, sigan leyendo. Este documento cubrirá lo que estamos buscando. Al abordar lo
La última frase podría escribirse de otra forma, tal vez de esta manera. `Siguiendo los siguientes puntos, las probabilidades de que podamos rápidamente unir o revisar tus contribuciones aumentarán`

2020-10-16 18:04 UTC, iamthismarvin commented
You were right. These translations sound better how you suggested them. Thank you!

2020-10-17 22:38 UTC, y-martinez approved these changes

2023-04-04 03:18 UTC, closed without merging