update select font for firefox close #3955
hasura/graphql-engine pull request #5923
Opened 2020-10-05 10:31 UTC by kimberrypi

### Description

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [x] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues
closes #3955

### Solution and Design
added `font-family: sans-serif;` to bootstrap overrides and react table overrides

### Steps to test and verify
*use firefox to check
1. `http://localhost:3000/data/schema/public`, click the dropdown
2. select a table and click the dropdown below filter
3. click the dropdown in the pagination

all should have sans-serif font

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2020-10-07 08:51 UTC, beerose commented on CHANGELOG.md
> +- console: fix select font family in firefox (#3955)
```suggestion
- console: fix select font family in firefox (close #3955) (#5923)
```

2020-10-07 08:51 UTC, beerose commented on CHANGELOG.md
>  - console: remove ONLY as default for ALTER TABLE in column alter operations (close #5512) #5706
```suggestion
- console: remove ONLY as default for ALTER TABLE in column alter operations (close #5512) (#5706)
```

2020-10-07 08:52 UTC, beerose approved these changes
Thanks for your PR! 😊

Approving console changes

2020-10-07 08:59 UTC, tirumaraiselvan approved these changes

2020-10-07 10:17 UTC, beerose commented on CHANGELOG.md
> +- console: fix select font family in firefox (close #3955) (#5923)
```suggestion
```

2020-10-07 10:44 UTC, beerose requested changes
Could you actually change the font to `'Gudea'`? We're using this font in the application, and it was the default in browsers other than Firefox before.

2020-10-10 07:47 UTC, kimberrypi commented
> Could you actually change the font to `'Gudea'`? We're using this font in the application, and it was the default in browsers other than Firefox before.

I updated it to be 'Gudea' :)

2020-11-05 05:33 UTC, mehtavishwa30 commented
Hello @kimberrypi!

Thanks so much for your contribution to Hasura OSS during the Hacktoberfest 2020! We'd love to send you some Hasura swag as a token of appreciation and you will be getting an email with the swag form shortly. ✨

2021-03-11 07:23 UTC, beerose commented
PR was merged in https://github.com/hasura/graphql-engine/commit/0c1133b3933e6e9362231869551235fd73403a69

2021-03-11 07:23 UTC, closed without merging