fixed linting in cli/source/stub/stub_test.go
hasura/graphql-engine pull request #5972
Opened 2020-10-09 11:19 UTC by ukitta555

### Description

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

#5831

### Solution and Design

Fixed linting errors. In general, just added error handling. ( if err != nil { t.Fatal(err) })

### Steps to test and verify

Run tests and check if everything is alright 👍 

### Limitations, known bugs & workarounds

N/A

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2020-10-09 11:20 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=5972) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=5972) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=5972) it.</sub>

2020-10-28 04:06 UTC, scriptonist commented
@ukitta555 I think we don't need to declare a new error variable each time, maybe you declare a `err` variable and reuse it ?

2020-10-28 04:11 UTC, scriptonist requested changes

2020-10-28 04:11 UTC, scriptonist commented on cli/migrate/source/stub/stub_test.go
> +	}
```suggestion
	err := m.Append(&source.Migration{Version: 1, Direction: source.Up})
	if err != nil {
		t.Fatal(errUp)
	}
```

2020-10-28 04:11 UTC, scriptonist commented on cli/migrate/source/stub/stub_test.go
> +	}
```suggestion
	err := m.Append(&source.Migration{Version: 1, Direction: source.Down})
	if err != nil {
		t.Fatal(errDown)
	}
```

2020-10-28 14:50 UTC, ukitta555 commented on cli/migrate/source/stub/stub_test.go
> +	}
fixed it! 👍

2020-10-29 02:49 UTC, scriptonist approved these changes

2020-10-29 04:23 UTC, arvi3411301 approved these changes

2020-10-29 05:42 UTC, merged

2020-11-05 05:21 UTC, mehtavishwa30 commented
Hello @ukitta555!

Thanks so much for your contribution to Hasura OSS during the Hacktoberfest 2020! We'd love to send you some Hasura swag as a token of appreciation. If you can share you email address, we will send you an email with the swag form shortly. ✨

2020-11-15 17:44 UTC, ukitta555 commented
> Hello @ukitta555!
> 
> Thanks so much for your contribution to Hasura OSS during the Hacktoberfest 2020! We'd love to send you some Hasura swag as a token of appreciation. If you can share you email address, we will send you an email with the swag form shortly. ✨

Hello!
It is ukitta555@gmail.com

2020-11-18 07:29 UTC, ukitta555 commented
Hello @mehtavishwa30 !
I didn't get the link to the form. Was I late with the email?

2020-11-18 07:44 UTC, mehtavishwa30 commented
Hey @ukitta555! Absolutely not!
Sorry, I was on a short break and just got back to work today. You should find your swag form in your mail shortly! 😉

2020-11-18 10:33 UTC, ukitta555 commented
> Hey @ukitta555! Absolutely not!
> Sorry, I was on a short break and just got back to work today. You should find your swag form in your mail shortly! 😉

Got it! Thanks a lot! 💯

2020-11-18 10:45 UTC, mehtavishwa30 commented
Awesome! Thanks for your patience! :)

On Wed, Nov 18, 2020 at 4:03 PM Vladyslav Nekriach <notifications@github.com>
wrote:

> Hey @ukitta555 <https://github.com/ukitta555>! Absolutely not!
> Sorry, I was on a short break and just got back to work today. You should
> find your swag form in your mail shortly! 😉
>
> Got it! Thanks a lot! 💯
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/hasura/graphql-engine/pull/5972#issuecomment-729589041>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AH3YAIJRKIMDRMHHQLT3HYTSQOPIBANCNFSM4SJ6LNPA>
> .
>