console: show only compatible postgres functions in computed fields section (close #5155)
hasura/graphql-engine pull request #5978
Opened 2020-10-10 13:59 UTC by GrizliK1988

Show only compatible postgres functions in computed fields section

### Description

When computed field is being created, user will see only  functions that have table row as one of arguments

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Console

### Related Issues

#5155 

### Solution and Design

At the beginning I planned to adjust SQL query to fetch only needed functions like
```
SELECT * FROM hdb_catalog.hdb_function_agg WHERE "input_arg_types"::jsonb @> '[{"schema":"table_schema","name":"table_name"}]'::jsonb;
```

Unfortunately backend doesn't accept json fields in where statements and I adjusted filtering on js side, which shouldn't be a problem, until user will have thousands of functions. 

### Steps to test and verify

There is a new test case in Cypress to verify functionality.

2020-10-14 03:55 UTC, shaonkabir8 approved these changes

2020-10-16 17:23 UTC, beerose requested changes
Thanks for your PR!

Filtering out functions that don't accept table row argument works great!

However, we could go one step forward and handle a few more requirements mentioned here: https://hasura.io/docs/1.0/graphql/core/schema/computed-fields.html#supported-sql-functions.

Specifically, we could:
* Check for the `function_type` and accept only STABLE or IMMUTABLE
* Check for the input arg types (we need 'b' — base or 'c' — composite)
<img width="483" alt="Screenshot 2020-10-16 at 19 16 48" src="https://user-images.githubusercontent.com/9019397/96288713-2acd7480-0fe4-11eb-9467-5a7015dd3f44.png">

2020-10-16 18:58 UTC, GrizliK1988 commented on console/cypress/integration/data/modify/test.ts
> +    it('See only functions for current table', passMTFunctionList);
Hi @beerose,

Thank you for your feedback! Described changes look good to me and I'll apply them in upcoming days.

2020-10-17 14:04 UTC, GrizliK1988 commented on console/cypress/integration/data/modify/test.ts
> +    it('See only functions for current table', passMTFunctionList);
Hi!

Code is updated. VOLATILE functions or functions with unsupported arguments are now filtered out.

2020-11-02 21:43 UTC, beerose approved these changes
Thank you again for your PR and for taking time to add tests! 🎉

Approving console changes

2021-01-15 11:54 UTC, beerose approved these changes
Console

2021-01-26 18:13 UTC, closed without merging