Server: support remote relationships to unions and interfaces types
hasura/graphql-engine pull request #6080
Opened 2020-10-27 13:03 UTC by codingkarthik

fixes #5875 

This PR adds support to joining remote fields of union and interface types. Earlier, we used to throw a validation error if the remote field is of either of the above mentioned types. 

### Description

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [x] Tests
- [ ] Other (list it)

### Related Issues

### Solution and Design

### Steps to test and verify

### Limitations, known bugs & workarounds

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2020-10-27 13:37 UTC, tirumaraiselvan approved these changes

2020-10-27 16:26 UTC, jberryman requested changes
Just a couple nits and that request for a good comment

2020-10-28 07:48 UTC, codingkarthik commented on server/src-lib/Hasura/RQL/DDL/RemoteRelationship/Validate.hs
> +    isValidType schemaDoc field =
I don't see any reason why we can't support remote relationships with enum fields as well. I've implemented the same in my following commit.

2020-10-28 16:42 UTC, jberryman commented on server/src-lib/Hasura/RQL/DDL/RemoteRelationship/Validate.hs
> +    isValidType schemaDoc field =
Ah nice!

2020-10-28 16:43 UTC, jberryman approved these changes

2020-10-29 11:30 UTC, merged