use hdb_catalog.gen_hasura_uuid() wrapped over gen_random_uuid()
hasura/graphql-engine pull request #6085
Opened 2020-10-28 13:13 UTC by tirumaraiselvan

### Description

Motivation is presented in https://github.com/hasura/graphql-engine/issues/4217

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Server

2020-10-28 15:44 UTC, 0x777 commented on server/src-rsr/initialise.sql
> +'select gen_random_uuid()' LANGUAGE SQL STABLE;
Ideally it has to be `select <schema-where-pgcrypto-is-installed>.gen_random_uuid()`. We don't do it on master but it'll be great if it is added as a TODO comment in the code.

2020-10-28 15:44 UTC, 0x777 requested changes
The comment mentioned above.

2020-11-03 11:07 UTC, 0x777 approved these changes

2020-11-03 11:11 UTC, codingkarthik approved these changes
LGTM

2020-11-03 12:09 UTC, merged