console: support volatile functions
hasura/graphql-engine pull request #6096
Opened 2020-10-29 10:15 UTC by beerose

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Console

2020-12-04 13:30 UTC, iykekings requested changes
Looks perfect to me. Great work @beerose. Can you check the error from Typescript I pointed out?

2020-12-04 13:36 UTC, beerose commented on console/src/components/Services/Common/Notification.tsx
>            dismissible: ['error', 'warning'].includes(level)
Fixed that recently in DT (https://github.com/DefinitelyTyped/DefinitelyTyped/pull/47560)
Will update deps

2020-12-04 14:31 UTC, beerose commented on console/src/components/Services/Common/Notification.tsx
>            dismissible: ['error', 'warning'].includes(level)
I'm bringing back the comment as `react-notification-system-redux` library needs to be updated to reflect types change.

2020-12-04 14:32 UTC, iykekings approved these changes

2020-12-04 14:36 UTC, tirumaraiselvan approved these changes
CL

2021-01-12 13:18 UTC, beerose commented
Closing in favour of https://github.com/hasura/graphql-engine-mono/pull/109

2021-01-12 13:18 UTC, closed without merging