server: avoid two circular imports
hasura/graphql-engine pull request #6134
Opened 2020-11-04 14:40 UTC by abooij

Ever seen this?
```
Build profile: -w ghc-8.10.2 -O1
In order, the following will be built (use -v for more details):
 - ci-info-0.1.0.0 (lib) (configuration changed)
 - graphql-parser-0.2.0.0 (lib) (configuration changed)
 - resource-pool-0.2.3.2 (lib) (configuration changed)
 - pg-client-0.1.0 (lib:pg-client) (configuration changed)
 - graphql-engine-1.0.0 (lib) (configuration changed)
 - graphql-engine-1.0.0 (exe:graphql-engine) (configuration changed)
Configuring library for ci-info-0.1.0.0..
Configuring library for resource-pool-0.2.3.2..
Configuring library for graphql-parser-0.2.0.0..
Preprocessing library for graphql-parser-0.2.0.0..
Building library for graphql-parser-0.2.0.0..
Preprocessing library for ci-info-0.1.0.0..
Building library for ci-info-0.1.0.0..
Preprocessing library for resource-pool-0.2.3.2..
Building library for resource-pool-0.2.3.2..
Configuring pg-client-0.1.0...
Preprocessing library for pg-client-0.1.0..
Building library for pg-client-0.1.0..
Configuring library for graphql-engine-1.0.0..
Preprocessing library for graphql-engine-1.0.0..
Building library for graphql-engine-1.0.0..
[ 82 of 200] Compiling Hasura.GraphQL.Parser.Class ( src-lib/Hasura/GraphQL/Parser/Class.hs, /home/vamshi/hasura/graphql-engine/server/dist-newstyle/build/x86_64-linux/ghc-8.10.2/graphql-engine-1.0.0/noopt/build/Hasura/GraphQL/Parser/Class.o, /home/vamshi/hasura/graphql-engine/server/dist-newstyle/build/x86_64-linux/ghc-8.10.2/graphql-engine-1.0.0/noopt/build/Hasura/GraphQL/Parser/Class.dyn_o ) [missing old dependency]
Configuring executable 'graphql-engine' for graphql-engine-1.0.0..
```
Yeah. So have all of us.

Due to some circular dependencies in `Hasura.GraphQL.Parser`, we kept seeing `Hasura.GraphQL.Parser.Class` getting pulled into cabal's build plan.

This fixes that, by avoiding the need for two `hs-boot` files: `server/src-lib/Hasura/GraphQL/Parser/Internal/Parser.hs-boot`, and `server/src-lib/Hasura/GraphQL/Parser/Class.hs-boot`.

Crucially, the `MonadParse` type class, the `QueryReusability` and `Parser` types, and the `ParserInput` type family have been moved to separate files to break some import loops. The remaining dependency of `Hasura.GraphQL.Parser.Collect` on `Hasura.GraphQL.Parser.Internal.Parser` has been avoided by passing the required definitions in `Hasura.GraphQL.Parser.Internal.Parser` as _arguments_ to `Hasura.GraphQL.Parser.Collect`, thus avoiding an import in the other direction.

2020-11-04 14:46 UTC, 0x777 approved these changes

2020-11-04 14:56 UTC, tirumaraiselvan approved these changes

2020-11-04 14:58 UTC, tirumaraiselvan requested changes
blocking because review by @lexi-lambda was requested.

2020-11-04 23:00 UTC, lexi-lambda approved these changes
> Due to some circular dependencies in `Hasura.GraphQL.Parser`, we kept seeing `Hasura.GraphQL.Parser.Class` getting pulled into cabal's build plan.

To be clear, is this a bug in `ghc` or `cabal-install`, or is this a fundamental problem?

Personally, I don’t mind circular modules at all, and I think it’s really nice to be able to put type definitions close to the functions associated with them. It also makes it much easier to exploit module abstraction boundaries. Using the `.Types` module approach, you can’t really define abstract types, since the implementation module needs to see the data constructors.

Having said that, there *are* downsides to circular modules. Due to the way GHC works, it has to recompile each strongly connected component of modules whenever one of its constituent modules changes. In this particular case, the strongly connected component is fairly small, and its modules change infrequently, so I don’t personally mind that issue. But I don’t care so much about it to die on this hill.

This particular PR seems fairly uninvasive (these types were already exported from an `Internal` module anyway), so I’m fine with it. I prefer the version with the circular module, but I seem to be in the minority about this.

2020-11-05 04:25 UTC, tirumaraiselvan approved these changes
no cl

2020-11-05 04:26 UTC, merged