Consistently log the request_id at the same level
hasura/graphql-engine pull request #6244
Opened 2020-11-23 16:59 UTC by lorenzo

### Description

Before this change, the server is logging requests with a different
shape.

- HTTPLog

```json
{
  "type": "http-log",
  "timestamp": "2020-11-23T17:30:41.782+0100",
  "level": "info",
  "detail": {
    "operation": {
      "query_execution_time": 8.6201e-05,
      "user_vars": {
        "x-hasura-role": "admin"
      },
      "request_id": "f579069a-23fc-4119-b2d8-4bab1a4e29e6",
      "response_size": 347,
      "request_read_time": 3.884e-06
    },
    "http_info": {
      "status": 200,
      "http_version": "HTTP/1.1",
      "url": "/foo",
      "ip": "127.0.0.1",
      "method": "GET",
      "content_encoding": "gzip"
    }
  }
}
```

- QueryLog

```json
{
"detail":  {
  "http_info" {...}
  "operation" {
    "query_execution_time": 0.001201056,
    "request_id": "e9bd9dd2-f5b3-4e26-9d88-9a39cff5acbb"
    ...
  }
},
"level": "info",
"timestamp": "2020-11-23T16:48:07.173+0000",
"type":	"http-log"
}
```

Notice that the `request_id` is nested in different levels in both
examples. This makes correlating the requests a bit more difficult than
it should be.

For instance, services like DataDog allow you to extract a json path as
a facet that can be used in searches. Since the `request_id` is at a
different level, it is not possible to correlate using the `request_id`.

After this change, the `QueryLog` will look like

```json
{
"detail":  {
  "http_info" {...}
  "operation" {
    "query_execution_time": 0.001201056,
    "request_id": "e9bd9dd2-f5b3-4e26-9d88-9a39cff5acbb"
    ...
  },
  "request_id": "e9bd9dd2-f5b3-4e26-9d88-9a39cff5acbb"
},
"level": "info",
"timestamp": "2020-11-23T16:48:07.173+0000",
"type":	"http-log"
}
```

The `request_id` is still present in the `operation` key for backward
compatibility.

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Server
- [ ] Console
- [ ] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues

### Solution and Design

### Steps to test and verify

### Limitations, known bugs & workarounds

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
- [ ] New types and typenames are correlated

#### Breaking changes

- [] No Breaking changes
- [x] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [x] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2020-11-27 07:14 UTC, ecthiender commented
Hi @lorenzo 

Can you help me understand the problem? I think I'm missing something.

You say:

> Notice that the `request_id` is nested in different levels in both examples. This makes correlating the requests a bit more difficult than it should be.

But from the above sample log lines, I can see in the current shape:

- http-log has `request_id` in `.detail.operation.request_id`
- query-log has `request_id` in `.detail.operation.request_id`

So they're both at the same level right? I think I'm missing something, can you help me with it?

2020-11-27 09:02 UTC, lorenzo commented
@ecthiender Sorry, I messed up the log outputs in the description. I had copied twice the same example from the log output thinking they were different. I have changed the description, but I'll summarize here again:

* http-log: `detail.operation.request_id`
* query-log: `detail.request_id`

After this change both will have: `detail.request_id`.

For backwards-compatibility, `http-log` will keep `detail.operation.request_id` as well.

2020-12-04 21:41 UTC, lorenzo commented
@ecthiender did that clarify the issue for you?

2020-12-05 05:36 UTC, ecthiender commented
@lorenzo yes it did. Thanks for the clarification. And sorry for the delay!

2020-12-05 05:37 UTC, ecthiender approved these changes

2020-12-15 06:10 UTC, tirumaraiselvan approved these changes
no changelog required

2020-12-21 01:36 UTC, tirumaraiselvan commented
@lorenzo Just to confirm, the docs actually show the log structure post your PR, correct? https://hasura.io/docs/1.0/graphql/core/deployment/logging.html#http-log-structure

2020-12-21 01:54 UTC, tirumaraiselvan commented
@lorenzo The docs would also require a change, correct? https://hasura.io/docs/1.0/graphql/core/deployment/logging.html#http-log-structure

As this is user-facing, a changelog would be preferred. Something like: "add request_id to top level in http-log"

2020-12-21 02:19 UTC, tirumaraiselvan requested changes
https://github.com/hasura/graphql-engine/pull/6244#issuecomment-748714232

2020-12-21 03:00 UTC, hgiasac commented
Just verify, will `detail.operation.request_id` field be removed on future release?

2020-12-21 10:58 UTC, tirumaraiselvan commented
> Just to confirm, will `detail.operation.request_id` field be removed on future release?

I don't think we can remove it without a major version bump. So it should not be removed anytime soon.

2021-01-09 11:53 UTC, lorenzo commented
@tirumaraiselvan jus to make sure, should I be changing the docs and adding a line to the changelog?

2021-01-11 06:35 UTC, tirumaraiselvan commented
@lorenzo Pls do!

2021-01-17 13:38 UTC, lorenzo commented
@tirumaraiselvan done. Can you please review again?

2021-01-18 10:06 UTC, tirumaraiselvan approved these changes

2021-01-19 17:26 UTC, closed without merging