docs: fix typo. errors for "hasura seed" => "hasura seeds"
hasura/graphql-engine pull request #6245
Opened 2020-11-23 23:14 UTC by codeliezel

### Description
This PR fixes typo errors for Hasura seeds.

### Changelog

- [x] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components
- [x] Docs

### Related Issues
https://discord.com/channels/407792526867693568/428469959530643466/778553964089180200

### Affected pages

2020-11-24 08:52 UTC, marionschleifer requested changes
@codeliezel I just checked with @scriptonist and he said the actual command is `hasura seed`, so let's go with this one 🙂

2020-12-07 16:01 UTC, marionschleifer requested changes
@codeliezel please address my comment below. Also, here there's an image that shouldn't be here.

2020-12-07 16:01 UTC, marionschleifer commented on docs/graphql/core/hasura-cli/hasura_seed_apply.rst
> +    hasura seed apply --file seed/1234_add_some_seed_data.sql
@codeliezel have you actually tried this out? I don't know if the actual folder structure will change names.

2020-12-17 09:18 UTC, closed without merging

2020-12-17 09:18 UTC, codeliezel commented
Moving to the mono-repo