Use <details> and <summary> for CollapsibleToggle, fix #6343
hasura/graphql-engine pull request #6416
Opened 2021-01-03 18:02 UTC by troglotit

### Description

This will add standard `<details>` and `<summary>` HTML tags, so we can listen for `toggle` event instead of handling clicks and keystrokes
### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [x] Console

### Related Issues

#6343

### Solution and Design

I've used `details` and `summary` tags, so I've used React's `onToggle` handler, which is not added at current `@types/react` version, so I've updated it. The behavior that `CollapsibleToggle` sometimes is controlled and sometimes is uncontrolled is preserved.

### Steps to test and verify

### Limitations, known bugs & workarounds

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2021-01-03 18:03 UTC, troglotit commented
This is my first PR, so I was not sure if Changelog update is needed. 🙂

2021-02-19 07:38 UTC, soorajshankar requested changes
Hi  @troglotit,
Thank you for the PR!! The code looks good!
 
I left a minor review comment that improves the typescript coverage, could you please resolve that too? 

Thanks!

2021-02-19 07:38 UTC, soorajshankar commented on console/src/components/Common/CollapsibleToggle/CollapsibleToggle.tsx
> +          if ((event.target as any).open !== isOpen) {
```suggestion
        onToggle={(event: React.ChangeEvent<HTMLDetailsElement>) => {
          // it gets called on mount if open=true, so we check if we really need to call handler
          if (event.target.open !== isOpen) {
```

2021-02-28 12:24 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=6416) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=6416) before we can accept your contribution.<br/>**5** out of **6** committers have signed the CLA.<br/><br/>:white_check_mark: codingkarthik<br/>:white_check_mark: nicuveo<br/>:white_check_mark: beerose<br/>:white_check_mark: troglotit<br/>:white_check_mark: 0x777<br/>:x: sassela<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=6416) it.</sub>

2021-02-28 12:27 UTC, khan297 approved these changes

2021-02-28 12:29 UTC, khan297 approved these changes

2021-02-28 12:29 UTC, troglotit commented
Hi, sorry for late response.
Checked it locally just to be sure.

2021-02-28 12:37 UTC, khan297 approved these changes

2021-02-28 12:37 UTC, khan297 commented
X

2021-03-02 09:12 UTC, soorajshankar commented
/heroku deploy

2021-03-03 09:24 UTC, soorajshankar approved these changes
console

2021-03-03 09:25 UTC, soorajshankar commented
/changelog ok

2021-03-03 11:15 UTC, soorajshankar requested changes

2021-03-03 14:10 UTC, troglotit commented on console/package.json
> +    "@types/react": "16.14.2",
I had troubles typing `<details>` tag, so that is why I updated. We can try checking "16.13.1" version which is React's version in package.json

2021-03-27 07:19 UTC, khan297 commented
ت

2021-03-27 07:21 UTC, khan297 commented on console/package.json
> +    "@types/react": "16.14.2",
ړ

2021-04-08 18:39 UTC, beerose commented
PR was merged: https://github.com/hasura/graphql-engine/commit/96ee013179b22dd49e1fa17f9c1136bf843978f3.

(we're merging shadowed PRs in a private monorepo, hence I'm closing this one)

Thanks for your contribution!

2021-04-08 18:39 UTC, closed without merging