cli: add deploy option (close #7349)
hasura/graphql-engine pull request #7426
Opened 2021-08-20 15:03 UTC by atb00ker

## WIP - TODO

- [ ] Writes Tests
- [ ] Add changes to documentation
- [ ] Test on an instance

### Description

Add `deploy` option in the cli to which performs the following actions:

```
$ hasura metadata apply
$ hasura migrate apply --all-databases
$ hasura metadata reload
```

### Changelog

- [X] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [ ] Server
- [ ] Console
- [X] CLI
- [ ] Docs
- [ ] Community Content
- [ ] Build System
- [ ] Tests
- [ ] Other (list it)

### Related Issues:
- #7349

### Solution and Design

We are invoking the `Run()` functions of CLI options from `metadata` 
and `migrate` options and performing metadata apply, migration apply and 
metadata reload actions in order.

### Steps to test and verify
Run: `hasura deploy --all-databases` and it should perform:
```
hasura metadata apply
hasura migrate apply --all-databases
hasura metadata reload
```

### Server checklist
#### Catalog upgrade
Does this PR change Hasura Catalog version?
- [X] No

#### Metadata
Does this PR add a new Metadata feature?
- [X] No

#### GraphQL
- [X] No new GraphQL schema is generated

#### Breaking changes
- [X] No Breaking changes

2021-08-20 15:04 UTC, atb00ker commented
Hi,

I am in the middle of testing, checking if I need to add docs & writing unit tests.
Just opening a PR for early feedback since I am new here! :smile:

2021-08-25 11:35 UTC, purush7 commented on cli/commands/migrate.go
> +func migrateCommonFlags(f *pflag.FlagSet, v *viper.Viper) {
```suggestion
func migrateCommonFlags(ec *cli.ExecutionContext, f *pflag.FlagSet, v *viper.Viper) {
```

2021-08-25 11:39 UTC, purush7 commented on cli/commands/migrate.go
> +func migrateCommonFlags(f *pflag.FlagSet, v *viper.Viper) {
```suggestion
func migrateCommonFlags(ecp cli.ExecutionContext, f *pflag.FlagSet, v *viper.Viper) {
f.StringVar(ecp.Source.Name, "database-name", "", "database on which operation should be applied")
 f.String("endpoint", "", "http(s) endpoint for Hasura GraphQL engine")
 f.BoolVar(ecp.DisableAutoStateMigration, "disable-auto-state-migration", false, "after a config v3 update, disable automatically moving state from hdb_catalog.schema_migrations to catalog state")
```

2021-08-25 11:39 UTC, purush7 commented on cli/commands/migrate.go
> +	migrateCommonFlags(f, v)
```suggestion
	migrateCommonFlags(&ec,f, v)
```

2021-08-25 12:43 UTC, purush7 commented on cli/integration_test/v3/deploy.go
> +				EC: ec,
```suggestion
				EC: ec,
				AllDatabases: true,
```

2021-08-25 13:44 UTC, purush7 commented on docs/graphql/core/hasura-cli/hasura_deploy.rst
> +    hasura metadata apply --admin-secret "<admin-secret>"
```suggestion
    hasura deploy --admin-secret "<admin-secret>"
```

2021-08-25 13:45 UTC, purush7 commented on docs/graphql/core/hasura-cli/hasura_deploy.rst
> +    hasura metadata apply --endpoint "<endpoint>"
```suggestion
    hasura deploy --endpoint "<endpoint>"
```

2021-08-25 13:48 UTC, purush7 requested changes
Everything is good except those suggested

2021-08-28 12:55 UTC, atb00ker commented
@purush7 
I got the first point, but regarding using `ecp`; while I can do that, I must point out, it's inconsistent with the other files; I am assuming ecp stands for execution context pointer; but the pointers in the other files are called `ec` only.

Assuming that the old code had this unintentionally done, I'll update the code in this file.
Just wanted to highlight this, thanks! :smile:

2021-08-28 20:50 UTC, atb00ker commented
@purush7  Done! 😄

2021-09-01 13:48 UTC, purush7 commented
Thanks, @atb00ker for your contribution

2021-09-29 06:15 UTC, closed without merging