update sample realtime-chat dependencies
hasura/graphql-engine pull request #7844
Opened 2021-11-25 02:22 UTC by arjunyel

### Description

### Changelog

- [ ] `CHANGELOG.md` is updated with user-facing content relevant to this PR. If no changelog is required, then add the `no-changelog-required` label.

### Affected components

- [X] Community Content

### Solution and Design

Updated to latest Apollo, React, create-react-app scripts, and switched to grapqhl-ws. Also added docker compose file for local development. Attempted to switch to Hook based components but was unsuccessful, kept running into infinite rerender errors. Rewrote the tutorial from https://hasura.io/blog/building-a-realtime-chat-app-with-graphql-subscriptions-d68cd33e73f/ with phrasing and code changes.

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [X] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [X] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [X] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [X] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2021-11-25 02:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=7844) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=7844) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=7844) it.</sub>

2021-11-29 09:27 UTC, praveenweb commented on community/sample-apps/realtime-chat/hasura/metadata/databases/databases.yaml
> +        from_env: HASURA_GRAPHQL_DATABASE_URL
Can we change this to `PG_DATABASE_URL` since that's the default for local dev setup and on Hasura Cloud?

2021-11-29 09:29 UTC, praveenweb requested changes
LGTM, except the env usage inside docker-compose.

2021-12-03 17:23 UTC, arjunyel commented
Fixed environment variable name

2021-12-07 09:00 UTC, praveenweb approved these changes

2021-12-07 13:15 UTC, closed without merging