partial submission for docs:capitalization of headings #8885
hasura/graphql-engine pull request #9072
Opened 2022-10-05 03:35 UTC by catcecilia

### Description
I updated some of the docs to follow the capitalization guideline for the issue referenced below

The reason why I am submitting partial is because I noticed others are interested in doing it too. I want to make sure that no one is overlapping in work. 

### Changelog

__Component__ : docs 

__Type__: enhancement

__Product__: community-edition

#### Short Changelog

Partial docs update regarding capitalization of headings.

#### Long Changelog

Looked through and updated capitalization of headings in .md and mdx in:
- graphql-engine/
- graphql-engine/server
- graphql-engine/scripts
- graphql-engine/rfcs
- graphql-engine/packaging

- docs/
- docs/wiki
- docs/static
- docs/src
- docs/scripts
- docs/public
- docs/docs/
- docs/docs/subscriptions 
- docs/docs/security
- docs/docs/schema

### Related Issues

issue #8885 

### Solution and Design

Partial solution, working together to finish all of docs would be a good suggestion. Also, shouldn't all documentation be updated? Not just the docs directory?

### Steps to test and verify

n/a

### Limitations, known bugs & workarounds

Limitation is human error

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

2022-10-05 03:35 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=9072) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=9072) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=9072) it.</sub>

2022-10-07 13:47 UTC, seanparkross commented
Hey @catcecilia 
Just curious as to why you closed this? Looked like a great PR...?

2022-10-07 13:52 UTC, catcecilia commented
I closed it because there was another naming convention issue which I hadn't taken account to posted under ( correct capitalization for hasura features #8884 )

I do not want to undo anyone's work so I'll be relooking at everything I've done over the weekend to make sure I did not made any incorrect lower cases in headings

2022-10-11 17:18 UTC, seanparkross commented
Hi @catcecilia actually the other PR needs a lot of work because it was done with script which needs to take into account a lot of edge cases. Your PR would be a much better starting point actually. If you want to reopen and ping me I will review it. Yes?

2022-10-18 14:54 UTC, seanparkross commented
Hi Cat. The PR is looking good. Please could you just revert changes to anything outside the docs directory... eg:

<img width="367" alt="Screenshot_2022-10-18_at_15_50_27" src="https://user-images.githubusercontent.com/94021366/196465731-cb4cb2d1-f635-4131-89b3-955d9263c6b8.png">

2022-10-20 11:11 UTC, seanparkross requested changes

2022-10-20 11:11 UTC, seanparkross commented on docs/docs/schema/postgres/computed-fields.mdx
> +## Computed fields in remote relationships
```suggestion
## Computed fields in Remote Relationships
```

2022-10-20 11:11 UTC, seanparkross commented on docs/docs/schema/postgres/computed-fields.mdx
> +## Computed fields in remote relationships
As this is a feature we're going to keep it title case.

2022-10-20 11:11 UTC, seanparkross commented on docs/docs/security/allow-list.mdx
> +## Enable Allow list
```suggestion
## Enable Allow List
```

2022-10-20 11:11 UTC, seanparkross commented on docs/docs/security/allow-list.mdx
> +## Enable Allow list
Since this is a feature we're going to keep it title case

2022-10-20 11:11 UTC, seanparkross commented on docs/docs/security/allow-list.mdx
> +## Open Allow list manager
```suggestion
## Open Allow List manager
```

Since this is a feature we're going to keep it title case

2022-10-20 11:11 UTC, seanparkross commented on docs/docs/security/allow-list.mdx
> +## Role-based Allow list
```suggestion
## Role-based Allow List
```

Since this is a feature we're going to keep it title case

2022-10-27 11:37 UTC, seanparkross approved these changes
Looks great! Thanks for the Hacktoberfest submission @catcecilia !!

2022-10-27 15:59 UTC, Stefmore02 commented
Hey! @catcecilia 

We truly appreciate your contribution to Hasura OSS during Hacktoberfest 2022! We'd love to send you some Hasura swag as a token of appreciation. Could you please send me an email to [estefani@hasura.io](mailto:estefani@hasura.io) with a reference of this PR so I can send you the swag form? ✨

2022-10-28 13:55 UTC, seanparkross commented
@catcecilia I just merged master back because there were conflicts. 

Please can you click and accept the CLA agreement in the message above before we're able to merge. 

Thanks

2022-10-28 15:42 UTC, catcecilia commented
@seanparkross done. my apologies on not agreeing to it sooner!

2022-10-28 17:43 UTC, closed without merging