Correct documentation capitalization (close #8884)
hasura/graphql-engine pull request #9083
Opened 2022-10-07 01:14 UTC by 3t8

### Description
Fix capitalization of Hasura and Hasura features throughout the documentation

### Related Issues
#8884 

### Solution and Design
Improved readability by capitalizing Hasura features

### Affected components

- [x] Docs

### Breaking changes

- [x] No Breaking changes:
- [ ] There are breaking changes

2022-10-07 01:14 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=9083) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=9083) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=9083) it.</sub>

2022-10-17 14:13 UTC, robertjdominguez requested changes
Thanks for this PR @3t8 🚀 

This is a huge improvement! I've suggested a change for `Data Federation` to change back to `Data federation` as this is a convention that is not Hasura-specific.

Additionally, we need to revert the changes in the `hasura-cli` directory, as these are automatically generated and will be overwritten. We can take these up internally 👍

2022-10-17 14:13 UTC, robertjdominguez commented on docs/docs/schema/postgres/remote-relationships/index.mdx
> +- **Data Federation**: With remote joins, the join, authorization, and consistency checks of added sources all happen at
```suggestion
- **Data federation**: With remote joins, the join, authorization, and consistency checks of added sources all happen at
```

2022-11-03 10:45 UTC, 3t8 commented
@robertjdominguez Updated with lowecase data federation

2022-11-09 18:08 UTC, robertjdominguez commented
@3t8, thanks for this work! Your implementation took cleverness and time, and we appreciate that ❤️ 

While we're not going to be able to merge your changes right now, we'd like to send you some swag to say thanks 🔥 

@Stefmore02 will be in touch soon 🚀

2022-11-09 18:08 UTC, closed without merging

2022-11-09 18:53 UTC, Stefmore02 commented
Hey @3t8 !

We truly appreciate your contribution to Hasura OSS during Hacktoberfest 2022! We'd love to send you some Hasura swag as a token of appreciation. Could you please send me an email to [estefani@hasura.io](mailto:estefani@hasura.io) with a reference of this PR so I can send you the swag form? ✨