Updated Screenshots In Docs (close #8883)
hasura/graphql-engine pull request #9087
Opened 2022-10-08 09:51 UTC by Sujithkumardola

### Description

Updated Screenshots In Databases Section of Docs.

Partially closes #8883 

### Changelog

#### Short Changelog

Screenshots updated to 2.10.1 in Databases section of docs.

#### Long Changelog

 updated Screenshots in
 
 databases/connect-db/index
 databases/postgres/citus-hyperscale-postgres/getting-started/cloud
 databases/postgres/citus-hyperscale-postgres/getting-started/docker
 databases/ms-sql-server/getting-started/cloud
 databases/ms-sql-server/getting-started/docker
 databases/bigquery/getting-started/docker

### Related Issues

Related Issue : #8883

2022-10-15 05:35 UTC, Sujithkumardola commented
Hey @seanparkross I updated the screenshots and you can have a preview here at [https://sujith37.vercel.app](https://sujith37.vercel.app])

If there is any other issue, please let me know.

2022-10-18 13:45 UTC, seanparkross requested changes

2022-10-18 13:45 UTC, seanparkross commented on docs/docs/databases/bigquery/getting-started/docker.mdx
> +<Thumbnail src='/img/databases/bigquery/connect-big-query-db_console_2.10.1.png' alt='Connect
For this image, there is a horizontal scrollbar left in the crop of the page. Please crop this out. Also, if possible, the name of the environment variable here is different to that which is displayed in the image just before it. Which isn't ideal. eg:

<img width="936" alt="Screenshot 2022-10-18 at 14 19 08" src="https://user-images.githubusercontent.com/94021366/196440940-7b2fff9c-2bc2-460d-8173-4a24d4991dae.png">

2022-10-18 13:45 UTC, seanparkross commented on docs/docs/databases/connect-db/index.mdx
> +<Thumbnail src='/img/databases/connect-db_step-1_console_2.10.1.png' alt='Connect default database' width='1000px' />
Please leave the setting on this image on "Environment Variable" as that is the preferred way of connecting to DBs. 

Please crop like the existing image as per the original and not the whole page. EG:
<img width="1042" alt="Screenshot 2022-10-18 at 14 21 55" src="https://user-images.githubusercontent.com/94021366/196441852-19022569-9d0d-42a3-85f7-78ae8cda113c.png">

2022-10-18 13:45 UTC, seanparkross commented on docs/docs/databases/ms-sql-server/getting-started/cloud.mdx
> +<Thumbnail src='/img/databases/ms-sql-server/track-tables_step-3_console_2.10.1.png' alt='Track tables' width='1000px' />
This is too wide. Please set the width so it's the same size as the actual UI. 


<img width="1725" alt="Screenshot 2022-10-18 at 14 26 29" src="https://user-images.githubusercontent.com/94021366/196442621-fc935ffb-3fa7-48ed-aa4f-44dddabeb32b.png">

2022-10-18 13:45 UTC, seanparkross commented on docs/docs/databases/ms-sql-server/getting-started/cloud.mdx
> +<Thumbnail src='/img/databases/ms-sql-server/track-foreign-key-rel_step-3_console_2.10.1.png' alt='Track relationships' width='1000px' />
Also too wide. Set to actual size of the UI. Any chance we could rename "People" to "Users" it looks more professional. 

<img width="1728" alt="Screenshot 2022-10-18 at 14 28 41" src="https://user-images.githubusercontent.com/94021366/196443591-7232e00c-21f0-4a1a-ba59-99da8929c17a.png">

2022-10-18 13:45 UTC, seanparkross commented on docs/docs/databases/ms-sql-server/getting-started/docker.mdx
>  <Thumbnail src='/img/databases/ms-sql-server/1-manage-databases.png' alt='Manage databases' width='1000px' />
Can you also do this image? It's now out of place with reference to the others.

2022-10-18 13:45 UTC, seanparkross commented on docs/docs/databases/ms-sql-server/getting-started/docker.mdx
> +<Thumbnail src='/img/databases/ms-sql-server/track-tables_step-3_console_2.10.1.png' alt='Track tables' width='1000px' />
Too wide.

2022-10-18 13:45 UTC, seanparkross commented on docs/docs/databases/ms-sql-server/getting-started/docker.mdx
> +<Thumbnail src='/img/databases/ms-sql-server/track-foreign-key-rel_step-3_console_2.10.1.png' alt='Track relationships' width='1000px' />
Too wide. Also could "People" be renamed "Users"

2022-10-19 16:08 UTC, Sujithkumardola commented
Hey @seanparkross, I made the changes

2022-10-19 16:44 UTC, Sujithkumardola commented
> Hey @seanparkross, I made the changes

have a preview here at [https://sujith37.vercel.app](https://sujith37.vercel.app]/)

2022-10-21 16:54 UTC, seanparkross approved these changes
Thanks! Looks good

2022-10-27 12:10 UTC, seanparkross commented
@Sujithkumardola sorry I hate to be the one to say this but there seems to be a red heart lock on the form fields in some of your shots. I'm not sure if I missed this last time. Sorry if I did. I'm not sure what it is. Maybe a browser extension?


![connect-db-cloud-cb5e0b81ade17fcf01a141323732208c](https://user-images.githubusercontent.com/94021366/198280634-456a5337-1695-4193-9d76-55acb1f99583.png)

2022-10-27 14:54 UTC, Sujithkumardola commented
> @Sujithkumardola sorry I hate to be the one to say this but there seems to be a red heart lock on the form fields in some of your shots. I'm not sure if I missed this last time. Sorry if I did. I'm not sure what it is. Maybe a browser extension?
> 
> 
> ![connect-db-cloud-cb5e0b81ade17fcf01a141323732208c](https://user-images.githubusercontent.com/94021366/198280634-456a5337-1695-4193-9d76-55acb1f99583.png)
> 
> 

As mentioned in the linked issue, I only updated the feature documentation and not the Cloud documentation.

2022-10-27 14:57 UTC, Sujithkumardola commented
> @Sujithkumardola sorry I hate to be the one to say this but there seems to be a red heart lock on the form fields in some of your shots. I'm not sure if I missed this last time. Sorry if I did. I'm not sure what it is. Maybe a browser extension?
> 
> 
> ![connect-db-cloud-cb5e0b81ade17fcf01a141323732208c](https://user-images.githubusercontent.com/94021366/198280634-456a5337-1695-4193-9d76-55acb1f99583.png)
> 
> 

Could you please specify the file location?

2022-10-28 20:22 UTC, Stefmore02 commented
Hey! @Sujithkumardola 

Thanks so much for your contribution to Hasura OSS during the Hacktoberfest 2022! We'd love to send you some Hasura swag as a token of appreciation and you will be getting an email with the swag form shortly.✨

2022-10-31 11:59 UTC, closed without merging