doc(ISSUE_TEMPLATE): use `.yml` format instead of `.md` (close #9062)
hasura/graphql-engine pull request #9089
Opened 2022-10-08 17:12 UTC by progfay

### Description

In this PR, I converted issue templates from `.md` to `.yml`.

### Changelog

No changes which user affected.

#### Short Changelog

use yml format on issue templates

#### Long Changelog

define issue form with YAML issue templates

### Related Issues

https://github.com/hasura/graphql-engine/issues/9062

### Steps to test and verify

You can check the content and design of issue form from below links:
- Bug report: https://github.com/progfay/hasura-graphql-engine/issues/new?assignees=&labels=k%2Fbug&template=01_bug_report.yml&title=%5BBug%5D%3A+
- Feature request: https://github.com/progfay/hasura-graphql-engine/issues/new?assignees=&labels=k%2Fenhancement&template=02_feature_request.yml&title=%5BRequest%5D%3A+

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2022-10-08 17:12 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=9089) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=9089) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=9089) it.</sub>

2022-10-13 06:55 UTC, progfay commented
Hello, @IAmTamal and @adas98012.

I converted Issue Templates from `.md` to `.yml`, please review my PR.

Thanks!

2022-10-13 07:16 UTC, IAmTamal commented
> Hello, @IAmTamal and @adas98012.
> 
> I converted Issue Templates from `.md` to `.yml`, please review my PR.
> 
> Thanks!

Now the thing is i was waiting to work on it but all of a sudden you made a PR
I was waiting as i was not assigned nor did i know if they even wanted these changes.

2022-11-11 19:37 UTC, dsandip requested changes

2022-11-11 19:37 UTC, dsandip commented on .github/ISSUE_TEMPLATE/01_bug_report.yml
> +      description: "Provide a clear description of what is the current behaviour."
```suggestion
      description: "Where is the issue being seen"
```

2022-11-11 19:37 UTC, dsandip commented on .github/ISSUE_TEMPLATE/01_bug_report.yml
> +  - type: textarea
```suggestion
  - type: textarea
    id: current-behaviour
    attributes:
      label: "Current Behaviour"
      description: "What is the current behaviour?"
    validations:
      required: false
  - type: textarea
```

2022-11-11 19:37 UTC, dsandip commented on .github/ISSUE_TEMPLATE/01_bug_report.yml
> +      required: true
```suggestion
      required: false
```

2022-11-11 19:37 UTC, dsandip commented on .github/ISSUE_TEMPLATE/01_bug_report.yml
> +      required: true
```suggestion
      required: false
```

2022-11-11 19:37 UTC, dsandip commented on .github/ISSUE_TEMPLATE/01_bug_report.yml
> +  - type: textarea
```suggestion
  - type: input
```

2022-11-11 19:37 UTC, dsandip commented on .github/ISSUE_TEMPLATE/01_bug_report.yml
> +  - type: textarea
```suggestion
  - type: input
```

2022-11-11 19:37 UTC, dsandip commented on .github/ISSUE_TEMPLATE/02_feature_request.yml
> +  - type: textarea
```suggestion
  - type: textarea
    id: solution
    attributes:
      label: "Describe the solution you'd like"
      description: "Provide a clear and concise description of what you want to happen."
    validations:
      required: false
  - type: textarea
```

2022-11-11 19:37 UTC, dsandip commented on .github/ISSUE_TEMPLATE/02_feature_request.yml
> +  - type: textarea
```suggestion
  - type: input
```

2022-12-20 18:26 UTC, Stefmore02 commented
Hey! @progfay 

Here's a friendly reminder to address the changes requested. Let us know if any questions pop out! 🤓

2023-01-24 16:40 UTC, Stefmore02 commented
Hey! @progfay 

Closing this PR due to inactivity. I encourage you to re-open it whenever you're ready to address the changes 🤓.

2023-01-24 16:40 UTC, closed without merging

2023-01-26 15:08 UTC, IAmTamal commented
> Hey! @progfay
> 
> Closing this PR due to inactivity. I encourage you to re-open it whenever you're ready to address the changes nerd_face.

Should i make the changes and make a PR , i originally opened this issue a long time back.