add italian translation for README.md
hasura/graphql-engine pull request #9096
Opened 2022-10-11 17:29 UTC by Francesca-Belfiore

### Description

### Changelog

__Component__ : server / cli / console / build 

__Type__: bugfix / feature / enhancement 

__Product__: community-edition

#### Short Changelog

Added the italian translation for the Readme.

#### Long Changelog

### Related Issues

### Solution and Design

### Steps to test and verify

### Limitations, known bugs & workarounds

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [ ] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [ ] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [ ] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [ ] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2022-10-11 17:29 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=9096) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=9096) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=9096) it.</sub>

2022-10-20 15:20 UTC, lucarestagno commented on translations/README.italian.md
> +essere trovate nella cartella [assets/brand](../assets/brand). Sentiti libero di userle nella tua
**typo**: `userle` -> `usarle`

2022-10-20 15:22 UTC, lucarestagno commented on translations/README.italian.md
> +Le traduzioni degli altri file possono essere trovate [qui](translations).
**suggestion**: I would use `Le traduzioni di altri file` 🙌

2022-10-20 15:24 UTC, lucarestagno commented on translations/README.italian.md
> +Hasura è un prodotto open source che accelera lo sviluppo API di 10 volte fornendoti all'istante [GraphQL](https://hasura.io/graphql/) o API REST con autorizzazione integrata sui tuoi dati.
**suggestion**: I would use `fornendoti all'istante API GraphQL or REST`

**suggestion**:  I would remove `sui tuoi dati`

2022-10-20 15:27 UTC, lucarestagno commented on translations/README.italian.md
> +* **Crea queries potenti**: Filtro, paginazione, ricerca pattern, inserimento in bulk, aggiornamento ed eliminazione mutazioni integrati
**rephrase**: I would use

`Filtri, paginazione, ricerca di pattern, e mutazioni di inserimento, aggiornamento ed eliminazione, anche in bulk`

2022-10-20 15:29 UTC, lucarestagno commented on translations/README.italian.md
> +* **Attiva webhook o funzioni serverless**: Inserisci/aggiorna/elimina eventi su Postgres ([leggi di più](event-triggers.md))
**todo**: I would use `Eventi di inserimento/aggiornamento/eliminazione su Postgres`

2022-10-20 15:31 UTC, lucarestagno commented on translations/README.italian.md
> +* **Admin UI & Migrazioni**: Migrazioni dell'UI dell'amministratore e delgli schemi ispirate a Rails.
**todo**: `Interfaccia utente di amministrazione & migrazioni degli schemi ispirate a Rails`

2022-10-20 15:33 UTC, lucarestagno commented on translations/README.italian.md
> +    - [Attiva webhook su eventi del database](#trigger-webhooks-on-database-events)
**suggestion**: I would use `Invoca` instead of `Attiva`

2022-10-20 15:39 UTC, lucarestagno commented on translations/README.italian.md
> +Le azioni sono un modo per estendere lo schema di Hasura con una business logic personalizzata utilizzando query e mutazioni ad hoc. È possibile aggiungere azioni ad Hasura per gestire vari casi d'us
**typo**: `buniness` -> `business` 😉

2022-10-20 15:44 UTC, lucarestagno requested changes
Thanks for your contribution Francesca!

You did a great job 🙌

I left some comments, would you mind looking at them?

Grazie 😉

2022-10-20 16:37 UTC, Francesca-Belfiore commented
Ciao! Thank you for the review! I will apply the corrections as soon as possible 😉

2022-10-21 07:37 UTC, lucarestagno approved these changes
Looks good to me! Thanks Francesca! 🙌

2022-10-21 09:57 UTC, closed without merging

2022-10-21 10:42 UTC, Francesca-Belfiore commented
You're welcome!
Oh, I saw you added the hacktoberfest label but since this repository is not participating the correct label to make this pr valid should be hacktoberfest-accepted. Could you please change it? Thank you in advance!

2022-10-25 13:41 UTC, Stefmore02 commented
Hey! @Francesca-Belfiore 

We truly appreciate your contribution to Hasura OSS during Hacktoberfest 2022! We'd love to send you some Hasura swag as a token of appreciation. Could you please send me an email to [estefani@hasura.io](mailto:estefani@hasura.io) with a reference of this PR so I can send you the swag form? ✨

2022-10-25 14:05 UTC, Francesca-Belfiore commented
Sure thanks, it would be a pleasure!

2022-10-25 14:44 UTC, Stefmore02 commented
Email received, I also forwarded the swag form for you to fill out. Thank you! 👍 ⭐