docs: create python version of ST recipe of abandoned carts (fixes #9913)
hasura/graphql-engine pull request #9936
Opened 2023-10-15 11:37 UTC by SoumyoPurkayastha

### Description

Added a python version for the JS handler in docs for the ST recipe of abandoned carts. Also added the missing bash commands for the JS handler in the docs

### Changelog

__Component__ : docs 

__Type__: enhancement 

__Product__: community-edition

#### Short Changelog

Added python handler for Abandoned Carts ST recipe

#### Long Changelog

### Related Issues

Close #9913 

### Solution and Design

### Steps to test and verify

### Limitations, known bugs & workarounds

### Server checklist

#### Catalog upgrade

Does this PR change Hasura Catalog version?
- [x] No
- [ ] Yes
  - [ ] Updated docs with SQL for downgrading the catalog 

#### Metadata

Does this PR add a new Metadata feature?
- [x] No
- [ ] Yes
  - Does `run_sql` auto manages the new metadata through schema diffing?
    - [ ] Yes
    - [ ] Not required
  - Does `run_sql` auto manages the definitions of metadata on renaming?
    - [ ] Yes
    - [ ] Not required
  - Does `export_metadata`/`replace_metadata` supports the new metadata added?
    - [ ] Yes
    - [ ] Not required

#### GraphQL
- [x] No new GraphQL schema is generated
- [ ] New GraphQL schema is being generated:
   - [ ] New types and typenames are correlated
   
   

#### Breaking changes

- [x] No Breaking changes
- [ ] There are breaking changes:

  1. Metadata API

     Existing `query` types:
     - [ ] Modify `args` payload which is not backward compatible
     - [ ] Behavioural change of the API
     - [ ] Change in response `JSON` schema
     - [ ] Change in error code
     

  2. GraphQL API

     Schema Generation:
     
     
     - [ ] Change in any `NamedType`
     - [ ] Change in table field names
     

     Schema Resolve:-
     
     - [ ] Change in treatment of `null` value for any input fields 
     

  3. Logging

     - [ ] Log `JSON` schema has changed
     - [ ] Log `type` names have changed

2023-10-15 11:37 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/hasura/graphql-engine?pullRequest=9936) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/hasura/graphql-engine?pullRequest=9936) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/hasura/graphql-engine?pullRequest=9936) it.</sub>

2023-10-16 11:53 UTC, SoumyoPurkayastha commented
Hey @robertjdominguez could you please review this PR and suggest changes if needed

2023-10-16 17:07 UTC, robertjdominguez requested changes
Thanks for this @SoumyoPurkayastha — please check the feedback, try it out, and see if you agree 👍

2023-10-16 17:07 UTC, robertjdominguez commented on docs/docs/scheduled-triggers/recipes/abandoned-cart.mdx
> +        server.sendmail(sender, recipient, msg.as_string())
```suggestion
     with smtplib.SMTP(smtp_server, smtp_port) as server:
          try:
              server.starttls()
              server.login(smtp_user, smtp_pass)
          except Exception as e:
              print(f"An error occurred while creating the SMTP server: {e}\nWe'll print the message to the terminal\n")
    
          # compose the email
          subject = f"You've left items in your cart, {user_name.split(' ')[0]}!"
          body = f"Hi {user_name.split(' ')[0]}, it seems you've left some items in your cart. Don't forget to check out!"
          sender = 'sender@SuperStore.com'
          recipient = user_email
    
          msg = MIMEMultipart()
          msg['From'] = sender
          msg['To'] = recipient
          msg['Subject'] = subject
          msg.attach(MIMEText(body, 'plain'))
    
          # send the email
          try:
              server.sendmail(sender, recipient, msg.as_string())
          except Exception as e:
              print(f"From: {msg['From']}\nTo: {msg['To']}\nSubject: {msg['Subject']}\n{body}")
```

Would you try a change like this to see if we can more elegantly handle users who don't have an SMTP server they can connect to? This helps illustrate the ease of use and [follows the convention here](https://github.com/Azanul/graphql-engine/blob/66c40f4ca31a42e74483ffa91f91616706618321/docs/docs/scheduled-triggers/recipes/daily-summary-email.mdx#L313-L320).

2023-10-17 15:49 UTC, robertjdominguez commented
Thanks, @SoumyoPurkayastha — I've approved this on our internal repo 🎉 

CI should pick this up shortly and merge it for you. We appreciate this contribution 🚀 

cc @Stefmore02

2023-10-17 17:19 UTC, closed without merging

2023-10-17 17:50 UTC, SoumyoPurkayastha commented
Thanks! Looking forward to making further contributions here 😁

2023-10-18 17:57 UTC, Stefmore02 commented
Hey @SoumyoPurkayastha!

Thanks so much for your contribution to Hasura OSS during Hacktoberfest 2023! 🎉 We'd love to send you some Hasura swag as a token of appreciation, please send me an email to estefani@hasura.io to send you our swag form.✨